<a href="https://colab.research.google.com/github/Minal-2007/PROJECTS-/blob/main/Copy_of_EV_Feature_recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df=pd.read_csv('/content/ElectricCarData_Clean.csv')

In [ ]:
df.head()

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
0,Tesla,Model 3 Long Range Dual Motor,4.6,233,450,161,940,Yes,AWD,Type 2 CCS,Sedan,D,5,55480
1,Volkswagen,ID.3 Pure,10.0,160,270,167,250,Yes,RWD,Type 2 CCS,Hatchback,C,5,30000
2,Polestar,2,4.7,210,400,181,620,Yes,AWD,Type 2 CCS,Liftback,D,5,56440
3,BMW,iX3,6.8,180,360,206,560,Yes,RWD,Type 2 CCS,SUV,D,5,68040
4,Honda,e,9.5,145,170,168,190,Yes,RWD,Type 2 CCS,Hatchback,B,4,32997

In [ ]:
df = df[['PriceEuro', 'Range_Km',
    'Seats',
    'BodyStyle',
    'PowerTrain',
    'RapidCharge',
    'Segment']]

In [ ]:
df.head(5)

   PriceEuro  Range_Km  Seats  BodyStyle PowerTrain RapidCharge Segment
0      55480       450      5      Sedan        AWD         Yes       D
1      30000       270      5  Hatchback        RWD         Yes       C
2      56440       400      5   Liftback        AWD         Yes       D
3      68040       360      5        SUV        RWD         Yes       D
4      32997       170      4  Hatchback        RWD         Yes       B

In [ ]:
def feature_pacakage(price):
  if price < 35000 :
    return "Basic"
  elif price > 60000 :
    return "Premium"
  else :
    return "Luxury"

def ev_category (range_km):
  if range_km < 250:
    return "City EV"
  elif range_km <450 :
    return "Mid Range EV"
  else :
    return "Full Range EV"

df['FeaturePackage'] = df['PriceEuro'].apply(feature_pacakage)
df['EVCategory'] = df['Range_Km'].apply(ev_category)

body_encoder = LabelEncoder()
power_encoder = LabelEncoder()
charge_encoder = LabelEncoder()
segment_encoder = LabelEncoder()
feature_encoder = LabelEncoder()
category_encoder = LabelEncoder()

df['BodyStyle'] = body_encoder.fit_transform(df['BodyStyle'])
df['PowerTrain'] = power_encoder.fit_transform(df['PowerTrain'])
df['RapidCharge'] = charge_encoder.fit_transform(df['RapidCharge'])
df['Segment'] = segment_encoder.fit_transform(df['Segment'])
df['FeaturePackage'] = feature_encoder.fit_transform(df['FeaturePackage'])
df['EVCategory'] = category_encoder.fit_transform(df['EVCategory'])

print("\nEncoded Dataset:")
df.head()

Encoded Dataset:

,PriceEuro,Range_Km,Seats,BodyStyle,PowerTrain,RapidCharge,Segment,FeaturePackage,EVCategory
0,55480,450,5,7,0,1,3,1,1
1,30000,270,5,1,2,1,2,0,2
2,56440,400,5,2,0,1,3,1,2
3,68040,360,5,6,2,1,3,2,2
4,32997,170,4,1,2,1,1,0,0

In [ ]:
X = df[['PriceEuro', 'Range_Km', 'Seats']]

In [ ]:
y_body = df['BodyStyle']
y_power = df['PowerTrain']
y_charge = df['RapidCharge']
y_segment = df['Segment']
y_feature = df['FeaturePackage']
y_category = df['EVCategory']

In [ ]:
X_train, X_test, y_body_train, y_body_test = train_test_split(
    X, y_body,
    test_size=0.2,
    random_state=42
)

_, _, y_power_train, y_power_test = train_test_split(
    X, y_power,
    test_size=0.2,
    random_state=42
)

_, _, y_charge_train, y_charge_test = train_test_split(
    X, y_charge,
    test_size=0.2,
    random_state=42
)

_, _, y_segment_train, y_segment_test = train_test_split(
    X, y_segment,
    test_size=0.2,
    random_state=42
)

_, _, y_feature_train, y_feature_test = train_test_split(
    X, y_feature,
    test_size=0.2,
    random_state=42
)

_, _, y_category_train, y_category_test = train_test_split(
    X, y_category,
    test_size=0.2,
    random_state=42
)

In [ ]:
body_model = RandomForestClassifier()
power_model = RandomForestClassifier()
charge_model = RandomForestClassifier()
segment_model = RandomForestClassifier()
feature_model = RandomForestClassifier()
category_model = RandomForestClassifier()

In [ ]:
body_model.fit(X_train, y_body_train)
power_model.fit(X_train, y_power_train)
charge_model.fit(X_train, y_charge_train)
segment_model.fit(X_train, y_segment_train)
feature_model.fit(X_train, y_feature_train)
category_model.fit(X_train, y_category_train)

RandomForestClassifier()

In [ ]:
body_pred = body_model.predict(X_test)
power_pred = power_model.predict(X_test)
charge_pred = charge_model.predict(X_test)
segment_pred = segment_model.predict(X_test)
feature_pred = feature_model.predict(X_test)
category_pred = category_model.predict(X_test)

print("\nMODEL ACCURACIES")

print("Body Style Accuracy:",
      accuracy_score(y_body_test, body_pred))

print("PowerTrain Accuracy:",
      accuracy_score(y_power_test, power_pred))

print("Charging Support Accuracy:",
      accuracy_score(y_charge_test, charge_pred))

print("Segment Accuracy:",
      accuracy_score(y_segment_test, segment_pred))

print("Feature Package Accuracy:",
      accuracy_score(y_feature_test, feature_pred))

print("EV Category Accuracy:",
      accuracy_score(y_category_test, category_pred))

MODEL ACCURACIES
Body Style Accuracy: 0.5714285714285714
PowerTrain Accuracy: 0.6666666666666666
Charging Support Accuracy: 1.0
Segment Accuracy: 0.6190476190476191
Feature Package Accuracy: 0.9047619047619048
EV Category Accuracy: 1.0

In [ ]:
print("\n========== USER INPUT ==========")

budget = float(input("Enter Budget (Euro): "))
range_km = int(input("Enter Desired Range (km): "))
seats = int(input("Enter Number of Seats: "))

user_data = [[budget, range_km, seats]]

========== USER INPUT ==========
Enter Budget (Euro): 45000
Enter Desired Range (km): 670
Enter Number of Seats: 5

In [ ]:
body_result = body_model.predict(user_data)
power_result = power_model.predict(user_data)
charge_result = charge_model.predict(user_data)
segment_result = segment_model.predict(user_data)
feature_result = feature_model.predict(user_data)
category_result = category_model.predict(user_data)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [ ]:
body_output = body_encoder.inverse_transform(body_result)
power_output = power_encoder.inverse_transform(power_result)
charge_output = charge_encoder.inverse_transform(charge_result)
segment_output = segment_encoder.inverse_transform(segment_result)
feature_output = feature_encoder.inverse_transform(feature_result)
category_output = category_encoder.inverse_transform(category_result)

In [ ]:
print("\n========== RECOMMENDATIONS ==========")

print("Recommended Body Style:",
      body_output[0])

print("Recommended PowerTrain:",
      power_output[0])

print("Charging Support:",
      charge_output[0])

print("Recommended EV Segment:",
      segment_output[0])

print("Recommended Feature Package:",
      feature_output[0])

print("Recommended EV Category:",
      category_output[0])

========== RECOMMENDATIONS ==========
Recommended Body Style: 1
Recommended PowerTrain: 2
Charging Support: 1
Recommended EV Segment: 2
Recommended Feature Package: Luxury
Recommended EV Category: Mid Range EV